Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.fridge.handlers.FunctionRequestHandler
      CodeUri: /Users/krishangpatney/Development/fridge/app
      Runtime: java17
      Architectures:
        - x86_64